config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'food_meals/create'
  root 'home#index'
  resources :meals

  get 'search_food', to: 'meals#search'

  resources :food_meals

  get 'users', to: 'users#index'
  resources :users,  except: [:index]

  get 'datetime', to: 'food_meals#datetime'
  get 'datetime_range', to: 'food_meals#datetime_range'

  get 'destroy_meal', to: 'meals#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :food_meals
  has_many :meals, through: :food_meals

  validates :name, presence: true, uniqueness: {case_sensitive: false},
            length: {minimum: 2, maximum: 25}
  validates :calories, presence: true

  def self.search(name)
    Food.where(:name => name).all
  end
end

app/models/food_meal.rb
class FoodMeal < ApplicationRecord
  belongs_to :food
  belongs_to :meal
  
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user
  has_many :food_meals
  has_many :foods, through: :food_meals

  validates :time, presence: true
  def self.last_meal
    Meal.last
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum status: { regular: 0, manager: 1, admin: 2 }
  has_many :meals, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

end

app/controllers/food_meals_controller.rb
class FoodMealsController < ApplicationController
  def create
    current_meal = Meal.last_meal
    FoodMeal.create(food_id: params[:food_id], meal_id: current_meal.id)

    current_foodmeal = FoodMeal.last
    if current_meal.eat_datetime
      current_foodmeal.eat_datetime = current_meal.eat_datetime
      current_foodmeal.date = current_meal.eat_datetime.to_date
    else
      current_meal.eat_datetime = Time.now
      current_foodmeal.eat_datetime = current_meal.eat_datetime
      current_foodmeal.date = current_meal.eat_datetime.to_date
    end
    current_foodmeal.save
    redirect_to food_meals_path
  end

  def index
    @daily_meal = FoodMeal.all
  end

  def destroy
    foodmeal = FoodMeal.find(params[:id])
    foodmeal.delete
    flash[:notice] = "succesfully removed"
    redirect_to food_meals_path
  end

  def datetime
    if params[:search].to_date != nil
      @date = params[:search].to_date
      @meals = FoodMeal.where('Date(eat_datetime) = ?', @date)
      respond_to do |format|
        format.js { render partial: 'food_meals/date_result' }
      end
    elsif params[:to] && params[:from] != nil
      @meals_group = FoodMeal.where(eat_datetime: params[:from].to_date...params[:to].to_date).order('eat_datetime DESC').group_by(&:date).values
      respond_to do |format|
        format.js { render partial: 'food_meals/range_result' }
      end
    end


  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
  end

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.user = current_user
    @meal.eat_datetime = params[:eat_datetime]
    if @meal.save
      respond_to do |format|
        format.js { render partial: 'meals/search' }
      end
    end
  end

  def search
    @food = Food.search(params[:search])
    respond_to do |format|
      format.js { render partial: 'meals/search_result' }
    end
  end

  def show

  end

  def destroy
    meals = Meal.all
    meals.each do |meal|
        if meal.foods.first == nil
          meal.delete
        end
    end
    redirect_to food_meals_path
  end

  private
    def meal_params
      params.require(:meal).permit(:user_id, :time)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @food_meals = FoodMeal.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted"
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_meals_helper.rb
module FoodMealsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/food_meals/_date.html.erb
<%= form_tag datetime_path, remote: true, method: :get do %>
  <div class="form-group row">
    <label for="example-date-input" class="col-2 col-form-label">Date</label>
    <div class="col-5">
      <%= text_field_tag :search, params[:search], class: "form-control", type: "date", value: "2019-08-19T13:45:00", id: "example-date-input" %>
    </div>
    <div class="">
      <div class="col-0">
        <%= text_field_tag :from, params[:from], class: "form-control", type: "date", value: "2019-08-19T13:45:00", id: "example-date-input" %>
      </div>
      <div class="col-0">
        Hystory From - To
        <%= text_field_tag :to, params[:to], class: "form-control", type: "date", value: "2019-08-19T13:45:00", id: "example-date-input" %>
      </div>
    </div>
    <div class="col-md-0">
      <%= submit_tag("Search", class: "btn btn-outline-success my-2 my-sm-0") %>
    </div>
  </div>
<% end %>

<div id="date-results">

</div>

app/views/food_meals/_date_result.html.erb
<div class="row">
  <div class="col-9">
    <% total_calories = 0 %>
      <table id="example" class="table table-dark table-bordered table-hover">
        <thead>
          <th scope="col">Food</th>
          <th scope="col">Calories</th>
          <th scope="col">Eat Date</th>
          <th scope="col">Eat Time</th>
          <th scope="col">Meals</th>
        </thead>
        <tbody>
          <% @meals.each do |meal| %>
          <% if meal.meal.user_id == current_user.id %>
            <% total_calories += meal.food.calories.to_i %>
              <tr>
                <td><%= meal.food.name %></td>
                <td><%= meal.food.calories %></td>
                <td><%= meal.eat_datetime.to_date%></td>
                <td><%= meal.eat_datetime.strftime("%I:%M")%></td>
                <td><%= meal.meal.time %></td>
                <td><%= link_to "remove", food_meal_path(meal), method: :delete, data: {confirm: 'Are you sure?'},
                                                                        class: 'btn btn-sm btn-warning' %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
  </div>
</div>
<% total_calories_for_progress = total_calories / 20 %>
<% if total_calories_for_progress <= 100 %>
  <div class="progress">
    <div class="progress-bar bg-success" role="progressbar" style="width: <%= total_calories_for_progress %>%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
      <%= total_calories %>
    </div>
  </div>
<% end %>
<% if total_calories_for_progress > 100 %>
  <div class="progress">
    <div class="progress-bar bg-danger" role="progressbar" style="width: <%= total_calories_for_progress %>%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">
      <%= total_calories %>
    </div>
  </div>
<% end %>

app/views/food_meals/_date_result.js.erb
document.querySelector('#date-results').innerHTML = '<%= j render 'food_meals/date_result.html' %>'

app/views/food_meals/_range_result.html.erb
<% @meals_group.each do |meals| %>
<div class="row">
  <div class="col-9">
    <% total_calories = 0 %>
        <table id="example" class="table table-dark table-bordered table-hover">
          <thead>
            <th scope="col">Food</th>
            <th scope="col">Calories</th>
            <th scope="col">Eat Date</th>
            <th scope="col">Eat Time</th>
            <th scope="col">Meals</th>
          </thead>
          <tbody>

        <% meals.each do |meal| %>
          <% if meal.meal.user_id == current_user.id %>
            <% total_calories += meal.food.calories.to_i %>
              <tr>
                <td><%= meal.food.name %></td>
                <td><%= meal.food.calories %></td>
                <td><%= meal.eat_datetime.to_date%></td>
                <td><%= meal.eat_datetime.strftime("%I:%M")%></td>
                <td><%= meal.meal.time %></td>
                <td><%= link_to "remove", food_meal_path(meal), method: :delete, data: {confirm: 'Are you sure?'},
                                                                        class: 'btn btn-sm btn-warning' %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <% total_calories_for_progress = total_calories / 20 %>
  <% if total_calories_for_progress <= 100 %>
    <div class="progress">
      <div class="progress-bar bg-success" role="progressbar" style="width: <%= total_calories_for_progress %>%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
        <%= total_calories %>
      </div>
    </div>
  <% end %>
  <% if total_calories_for_progress > 100 %>
    <div class="progress">
      <div class="progress-bar bg-danger" role="progressbar" style="width: <%= total_calories_for_progress %>%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">
        <%= total_calories %>
      </div>
    </div>
  <% end %>
<% end  %>

app/views/food_meals/_range_result.js.erb
document.querySelector('#range-results').innerHTML = '<%= j render 'food_meals/range_result.html' %>'

app/views/food_meals/index.html.erb
<%= render 'food_meals/date' %>
<div id="date-result" class=index>

</div>
<div id="range-results" class=index>

</div>
Today's Meals
<div class="row">
  <div class="col-9">
    <% total_calories = 0 %>
      <table id="example" class="table table-dark table-bordered table-hover">
        <thead>
          <th scope="col">Food</th>
          <th scope="col">Calories</th>
          <th scope="col">Eat Date</th>
          <th scope="col">Eat Time</th>
          <th scope="col">Meals</th>
        </thead>
        <tbody>
          <% @daily_meal.each do |meal| %>
          <% #ar vfiltrav bazis doneze da ifiltreba views doneze sachiroa food_meals table-shi user_id-is chamateba%>
          <% if meal.meal.user_id == current_user.id and meal.eat_datetime.to_date == Date.today %>
            <% total_calories += meal.food.calories.to_i %>
              <tr>
                <td><%= meal.food.name %></td>
                <td><%= meal.food.calories %></td>
                <td><%= meal.eat_datetime.to_date%></td>
                <td><%= meal.eat_datetime.strftime("%I:%M")%></td>
                <td><%= meal.meal.time %></td>
                <td><%= link_to "remove", food_meal_path(meal), method: :delete, data: {confirm: 'Are you sure?'},
                                                                        class: 'btn btn-sm btn-warning' %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
  </div>
</div>
<% total_calories_for_progress = total_calories / 20 %>
<% if total_calories_for_progress <= 100 %>
  <div class="progress">
    <div class="progress-bar bg-success" role="progressbar" style="width: <%= total_calories_for_progress %>%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
      <%= total_calories %> /2000
    </div>
  </div>
<% end %>
<% if total_calories_for_progress > 100 %>
  <div class="progress">
    <div class="progress-bar bg-danger" role="progressbar" style="width: <%= total_calories_for_progress %>%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">
      <%= total_calories %> /2000
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Welcome to CalorieManager</h1>

<%= link_to 'Sign out', destroy_user_session_path, method: :delete %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'CaloriesManager', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to 'New meal', new_meal_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Meals', food_meals_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Users', users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <% if current_user %>
            <a class="nav-link"><%= current_user.email %></a>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CaloriesManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/meals/_form.html.erb
<%= form_for @meal, remote: true do |f| %>
  <div>
    <div class="form-group row">
      <div class="form-group">
         <%= f.label :time, class:"col-sm-2 col-form-label" %></br>
         <%= f.label :Breakfast, 'Breakfast' %>
         <%= f.radio_button :time, 'Breakfast', :checked => true %>
         <%= f.label :Lunch, 'Lunch' %>
         <%= f.radio_button :time, 'Lunch' %>
         <%= f.label :Dinner, 'Dinner' %>
         <%= f.radio_button :time, 'Dinner' %>
         <div class="col-0">
           <%= text_field_tag :eat_datetime, params[:eat_datetime], class: "form-control", type: "datetime-local", value: Date.today, id: "example-datetime-local-input" %>
           When did you eat current food?</br>
           You can leave it blank if its today
         </div>

       </div>
      </div>
    <div class="form-group row col-sm-10">
      <%= f.submit class: "btn btn-primary btn-lg my-sm-3"%>
    </div>
  </div>
<% end %>

app/views/meals/_search.html.erb
<%= form_tag search_food_path, remote: true, method: :get do %>
  <div class="orm-group row no-padding text-center col-md-10">
    <div class="col-md-5">
      <%= text_field_tag :search, params[:search], class: "form-control mr-sm-2", placeholder: "Search food" %>
    </div >
    <div class="col-md-0">
      <%= submit_tag("Search", class: "btn btn-outline-success my-2 my-sm-0") %>
    </div>
  </div>
<% end %>

<div id="search-results">

</div>

app/views/meals/_search.js.erb
document.querySelector('#search').innerHTML = '<%= j render 'meals/search.html' %>'

app/views/meals/_search_result.html.erb
<% @food.each do |food| %>
<div class="orm-group row no-padding text-center col-md-12">
  <div >
    <%= food.name %>
    <%= food.calories %>:calories
  </div>
  <div class="">
    <%= link_to "Add", food_meals_path(:food_id => food.id), class: "btn btn-sm btn-success", method: :post %>
  </div>

</div>
<% end %>

app/views/meals/_search_result.js.erb
document.querySelector('#search-results').innerHTML = '<%= j render 'meals/search_result.html' %>'

app/views/meals/index.html.erb
<h1>meals</h1>

app/views/meals/new.html.erb
<h1>Add meal</h1>
<div>
    <%= render 'meals/form' %>
    <%= link_to 'Cancel', destroy_meal_path%>
    <div id="search">

    </div>
    <div id="datetime-form">

    </div>


available foods: pig, chicken, apple, bread, beans
</div>

app/views/users/index.html.erb
<h1 align="center">All Users</h1>
<div align="center">
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="card border-default" style="width: 20rem;">
        <div class="card bg-light">
          <li><h3><%= link_to user.email, user_path(user) %></h3></li>
          <% if current_user.status == "admin" || user.id == current_user.id  %>
            <li><%= link_to "Delete user", user_path(user), method: :delete,
                data: { confirm: "Are you sure?"}%></li>
            <li><%= link_to "Edit profile", edit_user_registration_path(user), class:"dropdown-item" %></li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="row">
    <div class="col-9">
      <% total_calories = 0 %>
          <table id="example" class="table table-dark table-bordered table-hover">
            <thead>
              <th scope="col">Food</th>
              <th scope="col">Calories</th>
              <th scope="col">Date</th>
              <th scope="col">Meals</th>
            </thead>
            <tbody>
              <% @food_meals.each do |meal| %>
                <% #ar vfiltrav bazis doneze da ifiltreba views doneze sachiroa food_meals table-shi user_id-is chamateba%>
                <% if meal.meal.user_id == params[:id].to_i %>
                  <% total_calories += meal.food.calories.to_i %>
                    <tr>
                      <td><%= meal.food.name %></td>
                      <td><%= meal.food.calories %></td>
                      <td><%= meal.created_at.to_date%></td>
                      <td><%= meal.meal.time %></td>
                      <% if current_user.id == meal.meal.user_id || current_user.status == "manager" || current_user.status == "admin"  %>
                        <td><%= link_to "remove", food_meal_path(meal), method: :delete, data: {confirm: 'Are you sure?'},
                                                                                class: 'btn btn-sm btn-warning' %></td>
                      <% end %>
                    </tr>
                  <% end %>
                <% end %>
            </tbody>
          </table>
  </div>
</div>
<% total_calories_for_progress = total_calories / 20 %>
<% if total_calories_for_progress <= 100 %>
  <div class="progress">
    <div class="progress-bar bg-success" role="progressbar" style="width: <%= total_calories_for_progress %>%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
      <%= total_calories %>
    </div>
  </div>
<% end %>
<% if total_calories_for_progress > 100 %>
  <div class="progress">
    <div class="progress-bar bg-danger" role="progressbar" style="width: <%= total_calories_for_progress %>%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">
      <%= total_calories %>
    </div>
  </div>
<% end %>